// Problem categories and their specific problems by language
export const PROBLEMS_BY_CATEGORY = {
  fr: {
    'Santé et Bien-être': [
      'Douleurs chroniques persistantes',
      'Stress quotidien élevé',
      'Qualité sommeil mauvaise',
      'Circulation sanguine réduite',
      'Fatigue constante chronique',
      'Manque relaxation quotidienne',
      'Mauvaise posture assise',
      'Douleurs articulations fréquentes',
      'Immunité faible récurrente',
      'Stress musculaire élevé',
    ],
    Mode: [
      'Confort vêtements insuffisant',
      'Usure rapide tissus',
      'Transpiration excessive fréquente',
      'Tailles grandes indisponibles',
      'Design non attractif',
      'Matériaux irritants peau',
      'Résistance lavage insuffisante',
      'Chaussures provoquent douleurs',
      'Manque personnalisation mode',
      'Prix souvent élevés',
    ],
    'Décoration Intérieure': [
      'Espaces mal optimisés',
      'Meubles difficilement adaptables',
      'Décoration coûte trop cher',
      'Solutions peu fonctionnelles',
      'Ambiance maison impersonnelle',
      'Éclairage mal adapté',
      'Manque de rangement',
      'Matériaux peu durables',
      'Nettoyage décoration complexe',
      'Esthétique non personnalisée',
    ],
    'Électronique et Gadgets': [
      'Batteries vite déchargées',
      'Câbles enchevêtrés fréquents',
      'Compatibilité appareils limitée',
      'Fragilité des gadgets électroniques',
      'Qualité son médiocre',
      'Prix trop élevés',
      'Gadgets rapidement obsolètes',
      'Sécurité données insuffisante',
      'Difficulté maintenance appareils',
      'Manque innovation pratique',
    ],
    'Produits pour Animaux': [
      'Ennui constant animaux',
      'Griffures meubles fréquentes',
      'Comportements destructeurs réguliers',
      'Alimentation non adaptée',
      'Manque stimulation mentale',
      'Besoins physiques négligés',
      'Produits non durables',
      'Nettoyage accessoires difficile',
      'Solutions peu ergonomiques',
      'Peu de personnalisation',
    ],
    Voyage: [
      'Confort limité trajets',
      'Organisation bagages inefficace',
      'Valises peu résistantes',
      'Accessoires non pratiques',
      'Coût solutions élevé',
      'Sécurité objets insuffisante',
      'Oreillers inconfortables transport',
      'Fatigue pendant déplacements',
      'Adaptateurs non universels',
      'Rangement accessoires problématique',
    ],
    'Compléments Alimentaires': [
      'Carences nutritionnelles fréquentes',
      'Compléments effets secondaires',
      'Absence certification qualité',
      'Suppléments peu efficaces',
      'Prix souvent élevés',
      'Incompatibilité avec allergies',
      'Problèmes digestion suppléments',
      'Faiblesse énergie quotidienne',
      'Solutions difficiles trouver',
      'Manque éducation clients',
    ],
    'Fitness et Sport': [
      'Blessures fréquentes exercices',
      'Manque équipement économique',
      'Solutions encombrantes domicile',
      'Difficulté motivation sportive',
      'Manque programmes personnalisés',
      'Faibles performances équipements',
      'Peu solutions débutants',
      'Accessoires rapidement inutilisables',
      'Difficulté entretien équipements',
      'Confort exercices insuffisant',
    ],
    'Produits Écologiques': [
      'Alternatives plastiques absentes',
      'Prix produits écologiques élevés',
      'Solutions peu pratiques',
      'Manque sensibilisation écologique',
      'Produits jetables excessifs',
      'Durabilité matériaux limitée',
      'Recyclage souvent complexe',
      'Disponibilité faible marché',
      'Esthétique produits négligée',
      'Adoption solutions lente',
    ],
  },
  en: {
    'Health & Wellness': [
      'Persistent chronic pain',
      'High daily stress',
      'Poor sleep quality',
      'Reduced blood circulation',
      'Chronic constant fatigue',
      'Lack of daily relaxation',
      'Poor sitting posture',
      'Frequent joint pain',
      'Recurring weak immunity',
      'High muscle stress',
    ],
    Fashion: [
      'Insufficient clothing comfort',
      'Rapid fabric wear',
      'Frequent excessive sweating',
      'Unavailable large sizes',
      'Unattractive design',
      'Skin-irritating materials',
      'Poor wash resistance',
      'Painful shoes',
      'Lack of fashion customization',
      'Often high prices',
    ],
    'Interior Decoration': [
      'Poorly optimized spaces',
      'Difficult-to-adapt furniture',
      'Expensive decoration',
      'Impractical solutions',
      'Impersonal home atmosphere',
      'Poor lighting',
      'Lack of storage',
      'Non-durable materials',
      'Complex decoration cleaning',
      'Non-customized aesthetics',
    ],
    'Electronics & Gadgets': [
      'Quick battery drain',
      'Frequent tangled cables',
      'Limited device compatibility',
      'Electronic gadget fragility',
      'Poor sound quality',
      'High prices',
      'Quickly obsolete gadgets',
      'Insufficient data security',
      'Difficult device maintenance',
      'Lack of practical innovation',
    ],
    'Pet Products': [
      'Constant pet boredom',
      'Frequent furniture scratches',
      'Regular destructive behaviors',
      'Unsuitable food',
      'Lack of mental stimulation',
      'Neglected physical needs',
      'Non-durable products',
      'Difficult accessory cleaning',
      'Poor ergonomic solutions',
      'Little customization',
    ],
    Travel: [
      'Limited journey comfort',
      'Inefficient luggage organization',
      'Non-resistant suitcases',
      'Impractical accessories',
      'High solution cost',
      'Insufficient object security',
      'Uncomfortable travel pillows',
      'Travel fatigue',
      'Non-universal adapters',
      'Problematic accessory storage',
    ],
    'Dietary Supplements': [
      'Frequent nutritional deficiencies',
      'Supplement side effects',
      'Lack of quality certification',
      'Ineffective supplements',
      'Often high prices',
      'Allergy incompatibility',
      'Supplement digestion problems',
      'Daily energy weakness',
      'Hard-to-find solutions',
      'Lack of customer education',
    ],
    'Fitness & Sports': [
      'Frequent exercise injuries',
      'Lack of economic equipment',
      'Bulky home solutions',
      'Sports motivation difficulty',
      'Lack of personalized programs',
      'Poor equipment performance',
      'Few beginner solutions',
      'Quickly unusable accessories',
      'Difficult equipment maintenance',
      'Insufficient exercise comfort',
    ],
    'Eco-Friendly Products': [
      'Missing plastic alternatives',
      'High eco-product prices',
      'Impractical solutions',
      'Lack of ecological awareness',
      'Excessive disposable products',
      'Limited material durability',
      'Complex recycling',
      'Low market availability',
      'Neglected product aesthetics',
      'Slow solution adoption',
    ],
  },
  ar: {
    'الصحة والعافية': [
      'آلام مزمنة مستمرة',
      'ضغط يومي عالي',
      'جودة نوم سيئة',
      'ضعف الدورة الدموية',
      'تعب مزمن مستمر',
      'قلة الاسترخاء اليومي',
      'وضعية جلوس سيئة',
      'آلام المفاصل المتكررة',
      'ضعف المناعة المتكرر',
      'إجهاد العضلات العالي',
    ],
    الموضة: [
      'عدم راحة الملابس',
      'تلف سريع للأقمشة',
      'تعرق مفرط متكرر',
      'عدم توفر المقاسات الكبيرة',
      'تصميم غير جذاب',
      'مواد تسبب تهيج الجلد',
      'مقاومة ضعيفة للغسيل',
      'أحذية مؤلمة',
      'نقص في تخصيص الأزياء',
      'أسعار مرتفعة غالباً',
    ],
    'الديكور الداخلي': [
      'مساحات غير مستغلة بشكل جيد',
      'أثاث صعب التكيف',
      'ديكور مكلف',
      'حلول غير عملية',
      'أجواء منزل غير شخصية',
      'إضاءة غير مناسبة',
      'نقص في التخزين',
      'مواد غير متينة',
      'تنظيف ديكور معقد',
      'جماليات غير مخصصة',
    ],
    'الإلكترونيات والأجهزة': [
      'بطاريات تنفد بسرعة',
      'كابلات متشابكة متكررة',
      'توافق محدود للأجهزة',
      'هشاشة الأجهزة الإلكترونية',
      'جودة صوت رديئة',
      'أسعار مرتفعة جداً',
      'أجهزة تصبح قديمة بسرعة',
      'أمان بيانات غير كافٍ',
      'صيانة أجهزة صعبة',
      'نقص في الابتكار العملي',
    ],
    'منتجات الحيوانات الأليفة': [
      'ملل دائم للحيوانات',
      'خدوش متكررة للأثاث',
      'سلوكيات تدميرية منتظمة',
      'طعام غير مناسب',
      'نقص في التحفيز العقلي',
      'إهمال الاحتياجات البدنية',
      'منتجات غير متينة',
      'تنظيف مستلزمات صعب',
      'حلول غير مريحة',
      'قلة التخصيص',
    ],
    السفر: [
      'راحة محدودة في الرحلات',
      'تنظيم أمتعة غير فعال',
      'حقائب غير متينة',
      'ملحقات غير عملية',
      'تكلفة حلول مرتفعة',
      'أمان غير كافٍ للأغراض',
      'وسائد سفر غير مريحة',
      'تعب أثناء التنقل',
      'محولات غير عالمية',
      'مشكلة تخزين الملحقات',
    ],
    'المكملات الغذائية': [
      'نقص تغذوي متكرر',
      'آثار جانبية للمكملات',
      'غياب شهادة الجودة',
      'مكملات غير فعالة',
      'أسعار مرتفعة غالباً',
      'عدم توافق مع الحساسية',
      'مشاكل هضم المكملات',
      'ضعف الطاقة اليومية',
      'حلول صعبة الإيجاد',
      'نقص تثقيف العملاء',
    ],
    'اللياقة والرياضة': [
      'إصابات متكررة في التمارين',
      'نقص المعدات الاقتصادية',
      'حلول كبيرة الحجم للمنزل',
      'صعوبة التحفيز الرياضي',
      'نقص البرامج المخصصة',
      'أداء ضعيف للمعدات',
      'قلة حلول المبتدئين',
      'ملحقات تصبح غير صالحة سريعاً',
      'صيانة معدات صعبة',
      'راحة تمارين غير كافية',
    ],
    'المنتجات الصديقة للبيئة': [
      'غياب بدائل البلاستيك',
      'أسعار منتجات بيئية مرتفعة',
      'حلول غير عملية',
      'نقص الوعي البيئي',
      'منتجات يمكن التخلص منها بكثرة',
      'متانة مواد محدودة',
      'إعادة تدوير معقدة',
      'توفر محدود في السوق',
      'جماليات منتجات مهملة',
      'تبني بطيء للحلول',
    ],
  },
};

// Countries by region translations
export const COUNTRIES_BY_REGION_TRANSLATIONS = {
  en: {
    'Middle East': {
      label: 'Middle East',
      countries: [
        'Saudi Arabia',
        'United Arab Emirates',
        'Kuwait',
        'Qatar',
        'Bahrain',
        'Oman',
        'Iraq',
        'Jordan',
        'Lebanon',
      ],
    },
    'North Africa': {
      label: 'North Africa',
      countries: ['Morocco', 'Algeria', 'Tunisia', 'Libya', 'Egypt'],
    },
    Europe: {
      label: 'Europe',
      countries: [
        'France',
        'Germany',
        'United Kingdom',
        'Italy',
        'Spain',
        'Netherlands',
        'Belgium',
        'Switzerland',
      ],
    },
  },
  fr: {
    'Middle East': {
      label: 'Moyen-Orient',
      countries: [
        'Arabie Saoudite',
        'Émirats Arabes Unis',
        'Koweït',
        'Qatar',
        'Bahreïn',
        'Oman',
        'Irak',
        'Jordanie',
        'Liban',
      ],
    },
    'North Africa': {
      label: 'Afrique du Nord',
      countries: ['Maroc', 'Algérie', 'Tunisie', 'Libye', 'Égypte'],
    },
    Europe: {
      label: 'Europe',
      countries: [
        'France',
        'Allemagne',
        'Royaume-Uni',
        'Italie',
        'Espagne',
        'Pays-Bas',
        'Belgique',
        'Suisse',
      ],
    },
  },
  ar: {
    'Middle East': {
      label: 'الشرق الأوسط',
      countries: [
        'المملكة العربية السعودية',
        'الإمارات العربية المتحدة',
        'الكويت',
        'قطر',
        'البحرين',
        'عمان',
        'العراق',
        'الأردن',
        'لبنان',
      ],
    },
    'North Africa': {
      label: 'شمال أفريقيا',
      countries: ['المغرب', 'الجزائر', 'تونس', 'ليبيا', 'مصر'],
    },
    Europe: {
      label: 'أوروبا',
      countries: [
        'فرنسا',
        'ألمانيا',
        'المملكة المتحدة',
        'إيطاليا',
        'إسبانيا',
        'هولندا',
        'بلجيكا',
        'سويسرا',
      ],
    },
  },
};
