// Problem categories and their specific problems by language
export const PROBLEMS_BY_CATEGORY = {
  fr: {
    'Santé et Bien-être': [
      'Douleurs chroniques persistantes',
      'Stress quotidien élevé',
      'Qualité sommeil mauvaise',
      'Circulation sanguine réduite',
      'Fatigue constante chronique',
      'Manque relaxation quotidienne',
      'Mauvaise posture assise',
      'Douleurs articulations fréquentes',
      'Immunité faible récurrente',
      'Stress musculaire élevé',
      'Problèmes digestifs chroniques',
      'Allergies saisonnières',
      'Maux de tête fréquents',
      'Problèmes de peau',
      'Troubles du métabolisme',
      "Manque d'énergie",
      'Problèmes respiratoires',
      'Troubles hormonaux',
      'Problèmes de concentration',
      'Troubles du sommeil',
    ],
    'Beauté et Cosmétiques': [
      'Vieillissement cutané',
      'Taches pigmentaires',
      'Acné persistante',
      'Peau déshydratée',
      'Cheveux abîmés',
      'Pellicules',
      'Ongles fragiles',
      'Cernes prononcées',
      'Rides précoces',
      'Pores dilatés',
      'Teint terne',
      'Rougeurs cutanées',
      'Cicatrices visibles',
      'Cellulite',
      'Vergetures',
      'Peau grasse',
      'Chute de cheveux',
      'Imperfections',
      'Poches sous les yeux',
      "Manque d'éclat",
    ],
    'Maison et Habitat': [
      'Espaces mal optimisés',
      'Désordre chronique',
      "Problèmes d'humidité",
      'Mauvaise isolation',
      'Manque de rangement',
      'Éclairage inadéquat',
      'Aération insuffisante',
      'Bruit excessif',
      'Encombrement',
      'Entretien difficile',
      'Problèmes de chauffage',
      'Mauvaise organisation',
      'Décoration dépassée',
      'Espace limité',
      'Problèmes de plomberie',
      'Sécurité insuffisante',
      'Mauvaise circulation',
      'Manque de fonctionnalité',
      'Problèmes électriques',
      'Confort insuffisant',
    ],
    'Technologie et Gadgets': [
      'Batteries peu durables',
      'Connexion instable',
      'Stockage insuffisant',
      'Performance lente',
      'Compatibilité limitée',
      'Sécurité vulnérable',
      'Interface complexe',
      'Prix élevé',
      'Obsolescence rapide',
      'Support technique limité',
      'Problèmes de synchronisation',
      'Mise à jour complexe',
      'Perte de données',
      'Surchauffe',
      'Bugs fréquents',
      'Autonomie limitée',
      'Fragilité matérielle',
      'Configuration difficile',
      'Maintenance coûteuse',
      'Accessibilité réduite',
    ],
    'Sport et Fitness': [
      'Manque de motivation',
      'Temps limité',
      'Résultats lents',
      'Blessures fréquentes',
      'Équipement inadapté',
      'Plateau de progression',
      'Récupération difficile',
      'Nutrition inadéquate',
      'Suivi inefficace',
      'Fatigue excessive',
      'Manque de guidance',
      'Objectifs mal définis',
      'Douleurs musculaires',
      'Équipement coûteux',
      'Manque de variété',
      'Problèmes de technique',
      'Stress articulaire',
      'Surmenage',
      'Démotivation',
      'Planification complexe',
    ],
    'Alimentation et Nutrition': [
      'Régime déséquilibré',
      'Allergies alimentaires',
      'Intolérances',
      'Digestion difficile',
      'Manque de variété',
      'Budget limité',
      'Préparation chronophage',
      'Conservation limitée',
      'Portions inadaptées',
      'Grignotage excessif',
      'Carences nutritionnelles',
      'Choix restreints',
      'Goût monotone',
      'Temps de cuisine',
      'Gaspillage alimentaire',
      'Régimes spéciaux',
      "Manque d'inspiration",
      'Stockage complexe',
      'Qualité variable',
      'Prix élevés',
    ],
    'Transport et Mobilité': [
      'Embouteillages fréquents',
      'Stationnement difficile',
      'Coûts élevés',
      'Pollution',
      'Retards réguliers',
      'Confort limité',
      'Maintenance coûteuse',
      'Sécurité insuffisante',
      'Options limitées',
      'Accessibilité réduite',
      'Fatigue des trajets',
      'Impact environnemental',
      'Stress routier',
      'Distance importante',
      'Horaires inadaptés',
      'Pannes fréquentes',
      'Services insuffisants',
      'Connexions limitées',
      'Temps perdu',
      'Conditions météo',
    ],
    'Éducation et Formation': [
      'Coûts élevés',
      'Temps limité',
      'Accès restreint',
      'Qualité variable',
      'Contenu dépassé',
      'Support inadéquat',
      'Progression lente',
      'Motivation fluctuante',
      'Certification complexe',
      'Ressources limitées',
      'Méthodes inefficaces',
      'Manque de pratique',
      'Évaluation stressante',
      'Flexibilité limitée',
      'Adaptation difficile',
      'Suivi insuffisant',
      'Engagement faible',
      'Rythme inadapté',
      'Objectifs flous',
      'Retour limité',
    ],
    'Travail et Productivité': [
      'Stress professionnel',
      'Équilibre vie-travail',
      'Communication difficile',
      'Gestion du temps',
      'Environnement inadapté',
      'Charge excessive',
      'Motivation basse',
      "Conflits d'équipe",
      'Organisation complexe',
      'Développement limité',
      'Reconnaissance insuffisante',
      'Outils inadaptés',
      'Formation limitée',
      'Salaire insuffisant',
      'Progression bloquée',
      'Tâches répétitives',
      'Feedback rare',
      'Autonomie limitée',
      'Responsabilités floues',
      'Support insuffisant',
    ],
    'Loisirs et Divertissement': [
      'Budget limité',
      'Temps restreint',
      'Options limitées',
      'Qualité variable',
      'Accessibilité réduite',
      'Planification complexe',
      'Groupes restreints',
      'Météo défavorable',
      'Équipement coûteux',
      'Transport difficile',
      'Disponibilité limitée',
      'Choix restreints',
      'Réservation complexe',
      'Prix élevés',
      'Horaires inadaptés',
      'Services limités',
      'Sécurité insuffisante',
      'Confort réduit',
      'Maintenance coûteuse',
      'Support limité',
    ],
    'Problèmes de libido et bien-être sexuel': [
      'Baisse de libido – Déséquilibre hormonal',
      'Dysfonction érectile – Mauvaise circulation',
      "Manque d'endurance – Fatigue sexuelle",
      "Sècheresse vaginale – Manque d'hydratation",
      'Baisse de fertilité – Qualité du sperme réduite',
      'Manque de testostérone – Vitalité masculine',
      'Ejaculation précoce – Manque de contrôle',
      'Orgasme difficile – Sensibilité réduite',
      'Troubles hormonaux – Déséquilibre endocrinien',
      "Fatigue après rapports – Manque d'énergie",
      "Faible circulation sanguine – Moins d'érection",
      'Manque de désir – Stress ou hormones',
      'Tension sexuelle faible – Manque de stimulation',
    ],
  },
  en: {
    'Health & Wellness': [
      'Chronic pain',
      'High stress levels',
      'Poor sleep quality',
      'Blood circulation issues',
      'Chronic fatigue',
      'Lack of relaxation',
      'Poor posture',
      'Joint pain',
      'Weak immunity',
      'Muscle tension',
      'Digestive problems',
      'Seasonal allergies',
      'Frequent headaches',
      'Skin issues',
      'Metabolism problems',
      'Low energy',
      'Respiratory issues',
      'Hormonal imbalance',
      'Focus problems',
      'Sleep disorders',
    ],
    'Beauty & Cosmetics': [
      'Skin aging',
      'Dark spots',
      'Acne',
      'Dry skin',
      'Damaged hair',
      'Dandruff',
      'Brittle nails',
      'Dark circles',
      'Early wrinkles',
      'Large pores',
      'Dull complexion',
      'Skin redness',
      'Visible scars',
      'Cellulite',
      'Stretch marks',
      'Oily skin',
      'Hair loss',
      'Blemishes',
      'Eye bags',
      'Lack of radiance',
    ],
    'Home & Living': [
      'Poor space optimization',
      'Chronic clutter',
      'Humidity problems',
      'Poor insulation',
      'Storage issues',
      'Inadequate lighting',
      'Poor ventilation',
      'Noise problems',
      'Overcrowding',
      'Difficult maintenance',
      'Heating issues',
      'Poor organization',
      'Outdated decor',
      'Limited space',
      'Plumbing problems',
      'Security concerns',
      'Poor circulation',
      'Lack of functionality',
      'Electrical issues',
      'Comfort issues',
    ],
    'Technology & Gadgets': [
      'Short battery life',
      'Unstable connection',
      'Limited storage',
      'Slow performance',
      'Compatibility issues',
      'Security vulnerabilities',
      'Complex interface',
      'High cost',
      'Quick obsolescence',
      'Limited support',
      'Sync problems',
      'Update issues',
      'Data loss',
      'Overheating',
      'Frequent bugs',
      'Limited battery',
      'Hardware fragility',
      'Setup difficulty',
      'Costly maintenance',
      'Poor accessibility',
    ],
    'Sports & Fitness': [
      'Lack of motivation',
      'Time constraints',
      'Slow results',
      'Frequent injuries',
      'Inadequate equipment',
      'Progress plateau',
      'Poor recovery',
      'Improper nutrition',
      'Ineffective tracking',
      'Excessive fatigue',
      'Lack of guidance',
      'Unclear goals',
      'Muscle pain',
      'Expensive equipment',
      'Lack of variety',
      'Technique issues',
      'Joint stress',
      'Overtraining',
      'Demotivation',
      'Complex planning',
    ],
    'Food & Nutrition': [
      'Unbalanced diet',
      'Food allergies',
      'Intolerances',
      'Digestive issues',
      'Limited variety',
      'Budget constraints',
      'Time-consuming prep',
      'Limited shelf life',
      'Portion control',
      'Excessive snacking',
      'Nutritional deficiencies',
      'Limited choices',
      'Taste monotony',
      'Cooking time',
      'Food waste',
      'Special diets',
      'Lack of inspiration',
      'Storage issues',
      'Variable quality',
      'High prices',
    ],
    'Transportation & Mobility': [
      'Traffic congestion',
      'Parking difficulties',
      'High costs',
      'Pollution',
      'Regular delays',
      'Limited comfort',
      'Costly maintenance',
      'Safety concerns',
      'Limited options',
      'Poor accessibility',
      'Travel fatigue',
      'Environmental impact',
      'Road stress',
      'Long distances',
      'Inconvenient schedules',
      'Frequent breakdowns',
      'Limited services',
      'Poor connections',
      'Time waste',
      'Weather conditions',
    ],
    'Education & Training': [
      'High costs',
      'Time limitations',
      'Limited access',
      'Variable quality',
      'Outdated content',
      'Poor support',
      'Slow progress',
      'Fluctuating motivation',
      'Complex certification',
      'Limited resources',
      'Ineffective methods',
      'Lack of practice',
      'Stressful assessment',
      'Limited flexibility',
      'Difficult adaptation',
      'Insufficient feedback',
      'Low engagement',
      'Unsuitable pace',
      'Unclear objectives',
      'Limited feedback',
    ],
    'Work & Productivity': [
      'Work stress',
      'Work-life balance',
      'Communication issues',
      'Time management',
      'Poor environment',
      'Workload',
      'Low motivation',
      'Team conflicts',
      'Complex organization',
      'Limited development',
      'Poor recognition',
      'Inadequate tools',
      'Limited training',
      'Low salary',
      'Career stagnation',
      'Repetitive tasks',
      'Rare feedback',
      'Limited autonomy',
      'Unclear responsibilities',
      'Insufficient support',
    ],
    'Leisure & Entertainment': [
      'Limited budget',
      'Time constraints',
      'Limited options',
      'Variable quality',
      'Poor accessibility',
      'Complex planning',
      'Group restrictions',
      'Weather issues',
      'Expensive equipment',
      'Transportation issues',
      'Limited availability',
      'Restricted choices',
      'Complex booking',
      'High prices',
      'Inconvenient schedules',
      'Limited services',
      'Safety concerns',
      'Comfort issues',
      'Costly maintenance',
      'Limited support',
    ],
    'Sexual Health & Libido Issues': [
      'Low libido - Hormonal imbalance',
      'Erectile dysfunction - Poor circulation',
      'Lack of endurance - Sexual fatigue',
      'Vaginal dryness - Lack of hydration',
      'Decreased fertility - Reduced sperm quality',
      'Low testosterone - Male vitality',
      'Premature ejaculation - Lack of control',
      'Difficult orgasm - Reduced sensitivity',
      'Hormonal disorders - Endocrine imbalance',
      'Post-coital fatigue - Lack of energy',
      'Poor blood circulation - Less erection',
      'Lack of desire - Stress or hormones',
      'Low sexual tension - Lack of stimulation',
    ],
  },
  ar: {
    'الصحة والعافية': [
      'آلام مزمنة',
      'مستويات توتر عالية',
      'جودة نوم سيئة',
      'مشاكل الدورة الدموية',
      'تعب مزمن',
      'نقص الاسترخاء',
      'وضعية جسم سيئة',
      'آلام المفاصل',
      'ضعف المناعة',
      'توتر العضلات',
      'مشاكل الهضم',
      'حساسية موسمية',
      'صداع متكرر',
      'مشاكل البشرة',
      'مشاكل التمثيل الغذائي',
      'طاقة منخفضة',
      'مشاكل تنفسية',
      'خلل هرموني',
      'مشاكل التركيز',
      'اضطرابات النوم',
    ],
    'الجمال ومستحضرات التجميل': [
      'شيخوخة البشرة',
      'البقع الداكنة',
      'حب الشباب',
      'جفاف البشرة',
      'تلف الشعر',
      'قشرة الرأس',
      'أظافر هشة',
      'هالات سوداء',
      'تجاعيد مبكرة',
      'مسام واسعة',
      'بشرة باهتة',
      'احمرار البشرة',
      'ندبات ظاهرة',
      'سيلوليت',
      'علامات التمدد',
      'بشرة دهنية',
      'تساقط الشعر',
      'عيوب البشرة',
      'انتفاخ تحت العين',
      'نقص الإشراق',
    ],
    'المنزل والمعيشة': [
      'سوء تنظيم المساحة',
      'فوضى مزمنة',
      'مشاكل الرطوبة',
      'عزل سيئ',
      'مشاكل التخزين',
      'إضاءة غير كافية',
      'تهوية سيئة',
      'مشاكل الضوضاء',
      'ازدحام',
      'صيانة صعبة',
      'مشاكل التدفئة',
      'تنظيم سيئ',
      'ديكور قديم',
      'مساحة محدودة',
      'مشاكل السباكة',
      'مخاوف أمنية',
      'تدوير سيئ',
      'نقص الوظائف',
      'مشاكل كهربائية',
      'مشاكل الراحة',
    ],
    'التكنولوجيا والأجهزة': [
      'عمر بطارية قصير',
      'اتصال غير مستقر',
      'تخزين محدود',
      'أداء بطيء',
      'مشاكل التوافق',
      'ثغرات أمنية',
      'واجهة معقدة',
      'تكلفة عالية',
      'تقادم سريع',
      'دعم محدود',
      'مشاكل المزامنة',
      'مشاكل التحديث',
      'فقدان البيانات',
      'ارتفاع الحرارة',
      'أخطاء متكررة',
      'بطارية محدودة',
      'هشاشة الأجهزة',
      'صعوبة الإعداد',
      'صيانة مكلفة',
      'إمكانية وصول سيئة',
    ],
    'الرياضة واللياقة البدنية': [
      'نقص الحافز',
      'قيود الوقت',
      'نتائج بطيئة',
      'إصابات متكررة',
      'معدات غير مناسبة',
      'توقف التقدم',
      'تعافي سيئ',
      'تغذية غير مناسبة',
      'تتبع غير فعال',
      'تعب مفرط',
      'نقص التوجيه',
      'أهداف غير واضحة',
      'ألم العضلات',
      'معدات مكلفة',
      'نقص التنوع',
      'مشاكل تقنية',
      'إجهاد المفاصل',
      'تدريب مفرط',
      'فقدان الحافز',
      'تخطيط معقد',
    ],
    'الطعام والتغذية': [
      'نظام غذائي غير متوازن',
      'حساسية الطعام',
      'عدم تحمل',
      'مشاكل الهضم',
      'تنوع محدود',
      'قيود الميزانية',
      'تحضير مستهلك للوقت',
      'مدة صلاحية محدودة',
      'التحكم في الحصص',
      'وجبات خفيفة مفرطة',
      'نقص غذائي',
      'خيارات محدودة',
      'رتابة المذاق',
      'وقت الطهي',
      'هدر الطعام',
      'حميات خاصة',
      'نقص الإلهام',
      'مشاكل التخزين',
      'جودة متغيرة',
      'أسعار مرتفعة',
    ],
    'النقل والتنقل': [
      'ازدحام مروري',
      'صعوبات وقوف السيارات',
      'تكاليف عالية',
      'تلوث',
      'تأخيرات منتظمة',
      'راحة محدودة',
      'صيانة مكلفة',
      'مخاوف السلامة',
      'خيارات محدودة',
      'إمكانية وصول سيئة',
      'تعب السفر',
      'تأثير بيئي',
      'توتر الطريق',
      'مسافات طويلة',
      'جداول غير مناسبة',
      'أعطال متكررة',
      'خدمات محدودة',
      'روابط سيئة',
      'إضاعة الوقت',
      'ظروف الطقس',
    ],
    'التعليم والتدريب': [
      'تكاليف عالية',
      'قيود زمنية',
      'وصول محدود',
      'جودة متغيرة',
      'محتوى قديم',
      'دعم ضعيف',
      'تقدم بطيء',
      'تحفيز متقلب',
      'شهادة معقدة',
      'موارد محدودة',
      'طرق غير فعالة',
      'نقص التطبيق',
      'تقييم مجهد',
      'مرونة محدودة',
      'تكيف صعب',
      'تغذية راجعة غير كافية',
      'مشاركة منخفضة',
      'وتيرة غير مناسبة',
      'أهداف غير واضحة',
      'ملاحظات محدودة',
    ],
    'العمل والإنتاجية': [
      'ضغط العمل',
      'توازن العمل والحياة',
      'مشاكل التواصل',
      'إدارة الوقت',
      'بيئة سيئة',
      'عبء العمل',
      'تحفيز منخفض',
      'نزاعات الفريق',
      'تنظيم معقد',
      'تطور محدود',
      'تقدير ضعيف',
      'أدوات غير مناسبة',
      'تدريب محدود',
      'راتب منخفض',
      'ركود وظيفي',
      'مهام متكررة',
      'ملاحظات نادرة',
      'استقلالية محدودة',
      'مسؤوليات غير واضحة',
      'دعم غير كافٍ',
    ],
    'الترفيه والتسلية': [
      'ميزانية محدودة',
      'قيود زمنية',
      'خيارات محدودة',
      'جودة متغيرة',
      'إمكانية وصول سيئة',
      'تخطيط معقد',
      'قيود المجموعة',
      'مشاكل الطقس',
      'معدات مكلفة',
      'مشاكل النقل',
      'توفر محدود',
      'خيارات مقيدة',
      'حجز معقد',
      'أسعار مرتفعة',
      'جداول غير مناسبة',
      'خدمات محدودة',
      'مخاوف السلامة',
      'مشاكل الراحة',
      'صيانة مكلفة',
      'دعم محدود',
    ],
    'مشاكل الرغبة الجنسية والصحة الجنسية': [
      'انخفاض الرغبة الجنسية - خلل هرموني',
      'ضعف الانتصاب - ضعف الدورة الدموية',
      'نقص التحمل - إرهاق جنسي',
      'جفاف مهبلي - نقص الترطيب',
      'انخفاض الخصوبة - ضعف جودة الحيوانات المنوية',
      'نقص التستوستيرون - الحيوية الذكورية',
      'القذف المبكر - ضعف التحكم',
      'صعوبة الوصول للنشوة - انخفاض الحساسية',
      'اضطرابات هرمونية - خلل في الغدد الصماء',
      'إرهاق ما بعد الجماع - نقص الطاقة',
      'ضعف الدورة الدموية - ضعف الانتصاب',
      'نقص الرغبة - التوتر أو الهرمونات',
      'ضعف التوتر الجنسي - نقص التحفيز',
    ],
  },
};
